### ISSUE TITLE
请问有知更鸟的模型可以更新吗？

### ISSUE THREAD

**Issue by Kin1024** [YCL0609/Honkai-Star-Rail-Character-model-display#1]
感谢你提供的工具，我是一个cosplay爱好者，这个3D预览特别方便用于我对服装和道具的制作。
希望能够更新知更鸟和其它已经露出的模型。
尤其需要知更鸟的武器，感谢！

**Comment by YCL0609** [comment]
这个项目的模型都是在模之屋(https://www.aplaybox.com/)获取的，目前我知道有知更鸟模型的都是在自己的QQ群进行配布，我并不知道如何加入这些群。

**Comment by Kin1024** [comment]
我知道通过关键词Koikatu能找到，但是并没有武器模型

**Comment by YCL0609** [comment]
那应该是策划还没有做完，毕竟离上线少说还有1.5个版本。
